name: 'Run any linter with reviewdog'
description: '🐶 Run any linter with reviewdog on pull requests to improve code review experience.'
author: 'xendk'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.'
  command:
    description: 'Command whose output is fed to reviewdog.'
    default: ''
  ### Flags for reviewdog ###
  format:
    description: 'Format name, see the output of `reviewdog -list` for possible values. Overrides the `errorformat` option.'
    default: ''
  errorformat:
    description: 'Custom error format, see https://github.com/reviewdog/errorformat. Ignored when `format` is used.'
    default: ''
  name:
    description: 'Name of linter, if `format` is used, defaults to the same name.'
    default: ''
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
    default: 'github-pr-check'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
runs:
  using: 'composite'
  steps:
    # - name: Install Reviewdog
    #   run: |
    #     wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $GITHUB_ACTION_PATH/ v0.11.0
    #   shell: bash
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_WORKDIR: ${{ inputs.workdir }}
        INPUT_COMMAND: ${{ inputs.command }}
        INPUT_FORMAT: ${{ inputs.format }}
        INPUT_ERRORFORMAT: ${{ inputs.errorformat }}
        INPUT_NAME: ${{ inputs.name }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_mode: ${{ inputs.filter_mode }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'check-square'
  color: 'purple'
